### ISSUE TITLE
/apis PUT method is not working

### ISSUE THREAD

**Issue by mortada-codes** [kubeshop/kusk-gateway#653] opened 2022-08-30 08:29 UTC
**Describe the bug**
when calling /apis PUT method it returns 405 
**To Reproduce**
1.  deploy a new api
2.  update it using /apis put
3. See error

**Expected behavior**
deploy a new api version 

**Desktop (please complete the following information):**
 - Kubernetes version: 1.24
 - Kube Gateway Version: 1.1.6

 
**Additional context**
[curl.txt](https://github.com/kubeshop/kusk-gateway/files/9451152/curl.txt)

**Comment by kylehodgetts** [comment] 2022-09-01 10:57
@mortada-codes the spec you are passing seems to be invalid, probably due to the escaped quotes

closing as can't reproduce

**Closed by kylehodgetts** 2022-09-01 10:57 UTC
Labels: kind/bug, area/api-server
